apple/RNCWebView.m

`_SwizzleHelperWK` -> `__SwizzleHelperWK`
Fixes the linker error due to re-use 
```
/Users/timlanahan/Library/Developer/Xcode/DerivedData/exodus-fnapplbgicmjxsbmzvtrtnsvzqsm/Build/Products/Debug-iphonesimulator/exodus.app/exodus
duplicate symbol '_OBJC_IVAR_$__SwizzleHelperWK._webView' in:
/Users/timlanahan/Library/Developer/Xcode/DerivedData/exodus-fnapplbgicmjxsbmzvtrtnsvzqsm/Build/Products/Debug-iphonesimulator/RNNFTViewer/libRNNFTViewer.a(RNNFTViewerView.o)
/Users/timlanahan/Library/Developer/Xcode/DerivedData/exodus-fnapplbgicmjxsbmzvtrtnsvzqsm/Build/Products/Debug-iphonesimulator/react-native-webview/libreact-native-webview.a(RNCWebView.o)
duplicate symbol '_OBJC_CLASS_$__SwizzleHelperWK' in:
/Users/timlanahan/Library/Developer/Xcode/DerivedData/exodus-fnapplbgicmjxsbmzvtrtnsvzqsm/Bu …
```

fix(ios): rename global to not overlap

---

apple/RNCWebView.m
src/WebView.android.tsx
src/WebView.ios.tsx
src/WebViewTypes.ts

This PR hardcodes a bunch of toggles and ensures that the safe defaults are always followed. This means consumers of this package won't be able to set any other values.
All
* Removal of the `injectJavascript` method
* allowFileAccessFromFileURLs = false
* allowUniversalAccessFromFileURLs = false
* injectedJavaScriptForMainFrameOnly = true
* injectedJavaScriptBeforeContentLoadedForMainFrameOnly = true
* mediaPlaybackRequiresUserAction = true
Android only
* allowsFullscreenVideo = false
* allowFileAccess = false
* setSupportMultipleWindows = true
* mixedContentMode = 'never'
iOS only config
* allowsInlineMediaPlayback = true
* allowsAirPlayForMediaPlayback = false
* useSharedProcessPool = false
* sharedCookiesEnabled = false
* enableApplePay = false
* onFileDownload = `() => …

chore: force secure defaults

---

android/src/main/java/com/reactnativecommunity/webview/RNCWebViewManager.java
apple/RNCWebView.m
example/examples/Messaging.tsx

This PR unifies the way `postMessage` works on both platforms.
* uses the `document` element rather than `window`, just to prevent processing any cross-origin requests
* simplify android implementation
* use `document` on iOS rather than `window`
We could also make this use the window and set a fake origin, this might be better in the long term.

chore: unify postMessage on iOS & Android

---

src/WebView.ios.tsx

* 12.5.6: https://support.apple.com/en-us/HT213428 -- August 31, 2022
* 13.6: https://support.apple.com/en-us/HT211288
We use 13.6.1: https://support.apple.com/en-us/HT210393#1361 -- August 12, 2020
* 14.8.1: https://support.apple.com/en-us/HT212868 -- October 26, 2021
* 15.7.1: https://support.apple.com/en-us/HT213490 -- October 27, 2022

Set minimum ios versions

---

src/WebView.android.tsx
src/WebView.ios.tsx
src/WebViewTypes.ts

Summary
Adds handler for unsupported os version. 
This should be rendered if provided, else defaults to the hardcoded response

feat(dapps): add handler for unsupported os version

---

src/WebViewTypes.ts

Regression from [PR](https://github.com/ExodusMovement/react-native-webview/pull/12).
Properly `type` component element prop.

fix: use correct type for component prop

---

.circleci/config.yml
.github/workflows/detox.yml
.github/workflows/ios-ci.yml
android/src/main/java/com/reactnativecommunity/webview/RNCWebViewManager.java
android/src/main/java/com/reactnativecommunity/webview/events/TopNewWindowEvent.kt
src/WebView.android.tsx
src/WebViewShared.tsx
src/WebViewTypes.ts

Implement `onOpenWindow` to intercept iframe openning as alternative of [this PR](https://github.com/ExodusMovement/react-native-webview/pull/17) to open iframes on android.
this implementation ins based on [original lib PR](https://github.com/react-native-webview/react-native-webview/pull/2640) and included only the minimal necessary android code to our usage.

feat(android): add `onOpenWindow` event

---

android/src/main/java/com/reactnativecommunity/webview/RNCWebViewManager.java

Permissions request in mobile was previously removed by security in [commit](https://github.com/ExodusMovement/react-native-webview/commit/b91a7c4d5630ee87976967dc3f5a7c2d70544820).
PR Adds `camera` permission support for android which is required for KYC verification (`face-id` and `identification id` capture)

feat: enable camera permission request for android

---

src/WebView.android.tsx
src/WebView.ios.tsx

To prevent some `TypeError: Cannot read property '_nativeTag' of null` errors occurring sometimes during webview reload

fix: add null checks for webViewRef

---

src/WebView.android.tsx
src/WebView.ios.tsx
src/WebViewShared.tsx
src/WebViewTypes.ts
src/__tests__/WebViewShared-test.js
src/__tests__/__snapshots__/WebViewShared-test.js.snap

This PR removes the restriction of only allowing to open up "https" URLs, and instead allows the webview to open up "bitcoin:" deeplinks.

fix: allow deep linking

---

src/WebViewShared.tsx
src/WebViewTypes.ts
src/__tests__/WebViewShared-test.js
src/__tests__/__snapshots__/WebViewShared-test.js.snap

This PR addresses https://github.com/ExodusMovement/react-native-webview/pull/21#discussion_r1619865694 to harden the library against misuse, essentially disallowing implicit wildcards by the usage of `startsWith` and disallowing invalid protocols.

fix: force the usage of actual protocol scheme

---

src/WebViewShared.tsx

This change fixes a specific bug content in https://pump.fun
pump.fun has a screen with a chart (https://pump.fun/qAVkvgHYsCWyhdcrqQs8RdLN3cJAMJVLrAtu5Copump) which is an iframe, this iframe has the URL starting with `blob`, so the `extractOrigin` function is extracting wrong the origin from the URL.
since I noticed that this function is redundant, I'm changing to get the origin from the `URL` object and checking it against the `origingWhitelist` 
```js
<WebView
style={styles.container}
source={{ uri: 'https://pump.fun/' }}
originWhitelist={['*']}
/>
```

fix: whitelist validation for iframes

---

src/WebViewShared.tsx

Modify `_passesWhitelist` to return only `true` or `false` instead of null
ref: https://github.com/ExodusMovement/magic-eden/pull/3001#issuecomment-2263096833

feat: return only falsy values in passesWhitelist function

---

android/src/main/java/com/reactnativecommunity/webview/RNCWebViewManager.java

We recently changed API endpoints for Veriff to use their enterprise API. However, that API returns session URLs with another endpoint so when requesting camera access, it doesn't work.

feat: allow veriff enterprise domains for camera access

---

apple/RNCWebView.m

**Problem**
The `events` for JS messages contain the origin URL that fired the js message. We have a bug today where a JS message event has incorrect origin URL. 
We read the origin URL from the webview, but if the message was fired after a new URL loading has been initiated on webview, the event would contain the current URL that was being loaded by the webview which would be incorrect. It should have the URL that fired the message instead of the current URL.
**Repro Steps**
Execute this js script from your test website and observe that the `event` generated by firing js message from `fireJSMessage();` contains https://exodus.com as the url.
```
function reproInCorrectOriginURL() {
// Start loading exodus.com
window.open('https://exodus.com', 'x');
 
// fire a custom js message …
```

fixing the origin URL for javascript messages

---

package.json

Do not publish `android/.gradle` on package release

chore: ignore android gradle on package release

---

apple/RNCWebView.m

Follow up from security [review](https://github.com/ExodusMovement/exodus-mobile/pull/21623#issuecomment-2328442373) to use `WKSecurityOrigin` which only sends the `origin` without extra params/queries towards hardening webview security
follow test plan from [PR](https://github.com/ExodusMovement/exodus-mobile/pull/21623)

fix: use WKSecurityOrigin in place of absoluteUrl

---

android/src/main/java/com/reactnativecommunity/webview/RNCWebViewManager.java
apple/RNCWebView.m
src/WebView.android.tsx
src/WebView.ios.tsx
src/__tests__/validation-test.js
src/validation.ts

This reverts the changes removing support for loading static html in the webview.
Prerequisite for https://github.com/ExodusMovement/exodus-mobile/pull/23174

revert: remove static html support

---

src/WebViewShared.tsx

This PR truncates the title to 512 characters.

fix: slice title to max 512 characters

---

android/src/main/java/com/reactnativecommunity/webview/RNCWebViewManager.java
apple/RNCWebView.m
apple/RNCWebViewManager.m
src/WebView.android.tsx
src/WebView.ios.tsx
src/WebViewShared.tsx
src/WebViewTypes.ts

This PR enhances security by restricting media capture permissions (camera) in RN WebView for iOS to a predefined whitelist of trusted domains. It ensures that only approved origins (`alchemy.veriff.com` and `magic.veriff.me`) are granted access. We are already doing the same for Android.
More context: https://github.com/ExodusMovement/exodus-mobile/pull/24202#pullrequestreview-2617868370

fix: enforce webview camera permission whitelist for ios

---

package.json

ensure we `android/build` is always excluded from npm package.

chore: exclude android/build from npm package

---

src/WebViewShared.tsx

The issue discovered in https://github.com/ExodusMovement/exodus-mobile/pull/24709#pullrequestreview-2667702215. Some dApp may send non-JSON content inside the `nativeEvent.data`. For example, https://minswap.org is sending this:
```
{
"target": 9037,
"url": "https://minswap.org/",
"data": "ready",
"title": "Minswap DEX | Multi-pool decentralized exchange on Cardano",
"canGoBack": false,
"loading": false,
"canGoForward": false
}
```
The fix is needed to unblock updating `@exodus/web3-cardano` with https://github.com/ExodusMovement/assets/pull/5312, which is needed for the Headless update in Mobile

feat: better handle invalid JSON

---

.github/workflows/android-ci.yml

Fix android CI failing here: https://github.com/ExodusMovement/react-native-webview/pull/40

chore: update android-ci packages

---

src/WebViewShared.tsx

React linking canOpenURL does not recognize `mailto` protocol but it can open the mailto url. I agreed with @633kh4ck that it is less hacky approach then the [one](https://github.com/ExodusMovement/react-native-webview/pull/44) I commited previously. Plus it is less code on the client side.
Towards https://github.com/ExodusMovement/exodus-mobile/pull/29519
```
```
```diff
--- a/src/screens/Web3/Browser.js
+++ b/src/screens/Web3/Browser.js
@@ -608,16 +608,23 @@ const Web3Browser = ({ navigation, route }) => {
injectedJavaScriptBeforeContentLoadedForMainFrameOnly
injectedJavaScriptForMainFrameOnly
source={{ uri: dappUrl }}
onError={handleError}
onLoadStart={handleLoadStart}
onLoadEnd={handleLoad}
onScroll={onScroll}
ref={webview}
+                      deeplinkWhitelist={[
+ …
```

fix: mailto cannot be opened

---

android/src/main/java/com/reactnativecommunity/webview/RNCWebViewManager.java

For `port` condition check, this is always going to fail for `scheme == "http"` because `==` in java compares object references, not values, so the origin is always going to remain without the port.

fix: compare strings, not object references
